name : gradle
on:
 push:
    branches:
            - master
            - main
            - release
 pull_request:
    branches:
            - master
            - main
            

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
    
    -  uses: actions/checkout@v2

    - name: setup jdk 8    
      uses: actions/setup-java@v1
      with:
         java-version: 1.8

    - name: give permissions to gradle
      run: chmod +x gradlew

    - name: build with gradle
      run: ./gradlew build
      
    - name: test with gradle
      run: ./gradlew test

    # - name: publish with gradle
    #   run: /gradlew publish

    # - name: deploy with gradle
    #   run: ./gradlew deploy



 
